// Curated demo dataset so CineMatch works fully offline / without a TMDb key.
// Poster/backdrop images use deterministic seeded placeholders (picsum.photos)
// so every run renders the same image per movie. Swap TMDB_API_KEY in .env
// to switch to live TMDb data with real posters automatically.

const poster = (seed) => `https://picsum.photos/seed/${seed}/500/750`;
const backdrop = (seed) => `https://picsum.photos/seed/${seed}-wide/1280/720`;

export const MOCK_MOVIES = [
  { id: 1001, title: "Neon Horizon", overview: "A rogue pilot races across a dying galaxy to deliver the one cargo that could save humanity.", genre_ids: [878, 28], vote_average: 8.4, release_date: "2024-06-14", runtime: 128, original_language: "en", poster_path: null, poster: poster("neon-horizon"), backdrop: backdrop("neon-horizon") },
  { id: 1002, title: "Paper Lanterns", overview: "Two estranged sisters reunite for one summer at their late grandmother's lakeside home.", genre_ids: [18, 10749], vote_average: 7.9, release_date: "2023-09-02", runtime: 111, original_language: "en", poster_path: null, poster: poster("paper-lanterns"), backdrop: backdrop("paper-lanterns") },
  { id: 1003, title: "The Quiet Static", overview: "A sound engineer discovers a frequency that lets him hear his own memories.", genre_ids: [53, 18], vote_average: 8.1, release_date: "2022-11-18", runtime: 104, original_language: "en", poster_path: null, poster: poster("quiet-static"), backdrop: backdrop("quiet-static") },
  { id: 1004, title: "Midnight Confetti", overview: "A wedding planner's perfect night unravels when every guest turns out to have a secret.", genre_ids: [35, 10749], vote_average: 7.2, release_date: "2024-02-09", runtime: 98, original_language: "en", poster_path: null, poster: poster("midnight-confetti"), backdrop: backdrop("midnight-confetti") },
  { id: 1005, title: "Iron Meridian", overview: "An ex-soldier turned smuggler is pulled back into a war he thought he'd escaped.", genre_ids: [28, 53], vote_average: 7.6, release_date: "2021-05-21", runtime: 132, original_language: "en", poster_path: null, poster: poster("iron-meridian"), backdrop: backdrop("iron-meridian") },
  { id: 1006, title: "Hollow Orchard", overview: "A folk-horror tale of a family farm where something in the soil remembers.", genre_ids: [27, 18], vote_average: 7.8, release_date: "2023-10-27", runtime: 106, original_language: "en", poster_path: null, poster: poster("hollow-orchard"), backdrop: backdrop("hollow-orchard") },
  { id: 1007, title: "Glasswing", overview: "A cartographer maps a city that redraws itself every night.", genre_ids: [14, 878], vote_average: 8.6, release_date: "2020-08-14", runtime: 119, original_language: "en", poster_path: null, poster: poster("glasswing"), backdrop: backdrop("glasswing") },
  { id: 1008, title: "Low Tide Radio", overview: "A small coastal town's last DJ broadcasts hope during a storm that won't end.", genre_ids: [18], vote_average: 8.0, release_date: "2022-03-11", runtime: 101, original_language: "en", poster_path: null, poster: poster("low-tide-radio"), backdrop: backdrop("low-tide-radio") },
  { id: 1009, title: "The Understudy", overview: "A theater actor takes over a lead role and slowly becomes the character she plays.", genre_ids: [53, 18], vote_average: 7.5, release_date: "2019-11-01", runtime: 109, original_language: "en", poster_path: null, poster: poster("understudy"), backdrop: backdrop("understudy") },
  { id: 1010, title: "Summit & Static", overview: "Two rival climbers are forced to share one rope on the mountain that killed both their fathers.", genre_ids: [18, 28], vote_average: 7.9, release_date: "2024-01-19", runtime: 116, original_language: "en", poster_path: null, poster: poster("summit-static"), backdrop: backdrop("summit-static") },
  { id: 1011, title: "Comet Season", overview: "Four friends spend one last night chasing a meteor shower before life pulls them apart.", genre_ids: [35, 18], vote_average: 7.3, release_date: "2023-06-30", runtime: 97, original_language: "en", poster_path: null, poster: poster("comet-season"), backdrop: backdrop("comet-season") },
  { id: 1012, title: "The Last Cartographer", overview: "In a flooding world, a map-maker races to chart the last dry land before it's gone.", genre_ids: [878, 12], vote_average: 8.2, release_date: "2021-09-24", runtime: 124, original_language: "en", poster_path: null, poster: poster("last-cartographer"), backdrop: backdrop("last-cartographer") },
  { id: 1013, title: "Velvet Circuit", overview: "An underground street-racing crew builds a car that isn't fully legal — or human.", genre_ids: [28, 878], vote_average: 7.4, release_date: "2020-07-03", runtime: 121, original_language: "en", poster_path: null, poster: poster("velvet-circuit"), backdrop: backdrop("velvet-circuit") },
  { id: 1014, title: "Salt & Marigold", overview: "A chef returns to her grandmother's restaurant to save it, one recipe at a time.", genre_ids: [35, 10749], vote_average: 8.0, release_date: "2024-05-10", runtime: 103, original_language: "en", poster_path: null, poster: poster("salt-marigold"), backdrop: backdrop("salt-marigold") },
  { id: 1015, title: "Static Choir", overview: "A deaf composer hears music again after an experimental implant — but not the music she expects.", genre_ids: [18, 878], vote_average: 8.5, release_date: "2022-10-14", runtime: 112, original_language: "en", poster_path: null, poster: poster("static-choir"), backdrop: backdrop("static-choir") },
  { id: 1016, title: "The Long Exhale", overview: "A grief counselor takes on a client who insists he can speak to the dead — and might be right.", genre_ids: [27, 53], vote_average: 7.7, release_date: "2019-10-04", runtime: 108, original_language: "en", poster_path: null, poster: poster("long-exhale"), backdrop: backdrop("long-exhale") },
  { id: 1017, title: "Paper Tigers United", overview: "A washed-up boxer trains a ragtag youth team for a tournament that could save their gym.", genre_ids: [18, 35], vote_average: 7.6, release_date: "2023-03-17", runtime: 114, original_language: "en", poster_path: null, poster: poster("paper-tigers"), backdrop: backdrop("paper-tigers") },
  { id: 1018, title: "Orbit of Small Things", overview: "An animated tale of a tiny satellite that just wants to come home.", genre_ids: [16, 10751], vote_average: 8.3, release_date: "2021-12-03", runtime: 92, original_language: "en", poster_path: null, poster: poster("orbit-small-things"), backdrop: backdrop("orbit-small-things") },
  { id: 1019, title: "The Fault in Our Static", overview: "A documentary crew embeds with a family living off-grid after the blackouts began.", genre_ids: [99], vote_average: 7.9, release_date: "2020-02-28", runtime: 95, original_language: "en", poster_path: null, poster: poster("fault-static"), backdrop: backdrop("fault-static") },
  { id: 1020, title: "Crimson Ledger", overview: "A forensic accountant uncovers a decades-old conspiracy hidden in her own firm's books.", genre_ids: [53, 18], vote_average: 8.1, release_date: "2024-04-05", runtime: 118, original_language: "en", poster_path: null, poster: poster("crimson-ledger"), backdrop: backdrop("crimson-ledger") },
  { id: 1021, title: "Kite Season", overview: "Set against monsoon skies, two childhood friends reconnect through a kite-flying festival.", genre_ids: [10749, 18], vote_average: 7.8, release_date: "2022-08-19", runtime: 105, original_language: "hi", poster_path: null, poster: poster("kite-season"), backdrop: backdrop("kite-season") },
  { id: 1022, title: "Ashfall Requiem", overview: "Survivors of a volcanic eruption must cross an ash-choked continent to reach the last radio signal.", genre_ids: [28, 12], vote_average: 7.5, release_date: "2023-11-22", runtime: 135, original_language: "en", poster_path: null, poster: poster("ashfall-requiem"), backdrop: backdrop("ashfall-requiem") },
  { id: 1023, title: "The Marionette's Daughter", overview: "A puppeteer's estranged daughter inherits his workshop — and the strings attached to it.", genre_ids: [14, 27], vote_average: 8.0, release_date: "2021-10-08", runtime: 110, original_language: "en", poster_path: null, poster: poster("marionette-daughter"), backdrop: backdrop("marionette-daughter") },
  { id: 1024, title: "Static Bloom", overview: "In a near-future botanical lab, a scientist grows a flower that reacts to human emotion.", genre_ids: [878, 18], vote_average: 8.4, release_date: "2024-07-01", runtime: 107, original_language: "en", poster_path: null, poster: poster("static-bloom"), backdrop: backdrop("static-bloom") },
];
